### ISSUE TITLE
Responses should be JSON

### ISSUE THREAD

**Issue by PipeItToDevNull** [PipeItToDevNull/pastebin-swa#7]
```
2024-07-18 00:57:43.205 ERROR: POST request to URL: https://victorious-wave-0a02a5a0f.5.azurestaticapps.net/api/upload failed
2024-07-18 00:57:43.206 ERROR: Traceback (most recent call last):
  File "/var/TechSupportBot/techsupport_bot/core/http.py", line 218, in process_http_response
    response_json = await response_object.json()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1176, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://victorious-wave-0a02a5a0f.5.azurestaticapps.net/api/upload')
```

**Comment by PipeItToDevNull** [comment]
Check what Linx returns and maybe emulate that

**Comment by PipeItToDevNull** [comment]
Linx by default responds in plain text but can respond in JSON

**Comment by PipeItToDevNull** [comment]
Can a flag be added to the API to request plain or JSON?

**Comment by PipeItToDevNull** [comment]
Until it returns more than a plaintext link this isnt needed
